FROM node:20.11-alpine

WORKDIR /app


COPY front-end/package.json ./package.json
# COPY front-end/yarn.lock ./yarn.lock

# RUN yarn install --frozen-lockfile
RUN yarn install 

COPY front-end/ ./


EXPOSE 3001

CMD ["yarn", "run", "dev"]
